### ISSUE TITLE
Plugin and windows "dot files"

### ISSUE THREAD

**Issue by roose** [Kazakuri/hain-plugin-cmd#1]
If we have a cmdrc.bat, e.g. https://gist.github.com/gimmi/6079390
when run some command we see many many cmd windows before run that command
![hain-cmd](https://cloud.githubusercontent.com/assets/277651/14043536/80c0c27c-f2af-11e5-9cbc-2057cf6fb385.gif)

**Comment by Kazakuri** [comment]
Looks like it's an issue with the behavior of spawn, switching to execFile in 0a4a704 should fix it.

P.S: This cmdrc.bat thing is cool, I never knew you could do that :+1:
